### ISSUE TITLE
Media query stays even if I delete it from code

### ISSUE THREAD

**Issue by yagee** [SassNinja/postcss-combine-media-query#1]
Thx for the plugin!

I have a boilerplate project with Gulp 4 wich watches the input.css and runs all of postcss plugins one by one.

Example input:
```css
.foo {
  color: red;

  @media (min-width: 375px) {
    color: blue;
  }
}
```

Output's correct:
```css
.test {
  color: red;
}

@media (min-width: 375px) {
  color: blue;
}
```

But if I remove `@media` from my code 

Input 2:
```css
.foo {
  color: red;
}
```

Output's still the same:
```css
.test {
  color: red;
}

@media (min-width: 375px) {
  color: blue;
}
```

If I stop my Gulp 4 task (watch) and re-run task again - all seems Ok, but until I write/delete some media queries.
