### ISSUE TITLE
feature_request(option): combine different media queries for consistency

### ISSUE THREAD

**Issue by Kristinita** [SassNinja/postcss-combine-media-query#10]
### 1. Summary

It would be nice if postcss-combine-media-query could combine different media queries that user’s CSS will consistent.

### 2. Problem

In my projects I use 2 types of media queries: `@media screen and (orientation: landscape)` and `@media screen and (orientation: portrait)`. But third-party CSS tools for my projects may have different media queries.

For example, I use [**Bulma-stylus**](https://github.com/groenroos/bulma-stylus). I created the file `bulma-modules.styl` with the content:

```stylus
/* [INFO] I imported Bulma markup for tags styling */
@import "../../../../../node_modules/bulma-stylus/stylus/utilities/_all.styl"
@import "../../../../../node_modules/bulma-stylus/stylus/elements/tag.styl"
```

I compiled Stylus to CSS. My compiled file `bulma-modules.css` contains these lines:

```css
@media screen and (min-width: 1024px) {
	/* CSS properties */
}

@media screen and (max-width: 1023px) {
	/* CSS properties */
}
```

I don’t use `min-width: 1024px` and `max-width: 1023px`. These media queries are inconsistent with my another code. I need automatic changing `min-width: 1024px` to `orientation: landscape` and `max-width: 1023px` to `orientation: portrait`, but I don’t know, how I can do it.

### 3. Example of desired behavior

postcss-combine-media-query configuration:

```coffee
options:
	processors: [
		require("postcss-combine-media-query")
			"min-width: 1024px": "orientation: landscape"
			"max-width: 1023px": "orientation: portrait"
	]
```

Input 1:

```css
@media screen and (min-width: 1024px) {
	color: red;
}

@media screen and (max-width: 1023px) {
	color: yellow;
}
```

Output 1:

```css
@media screen and (orientation: landscape) {
	color: red;
}

@media screen and (orientation: portrait) {
	color: yellow;
}
```

Input 2:

```css
@media screen and (orientation: landscape) {
	background-color: yellow;
}

@media screen and (min-width: 1024px) {
	color: red;
}

@media screen and (orientation: portrait) {
	background-color: blue;
}

@media screen and (max-width: 1023px) {
	color: green;
}
```

Output 2:

```css
@media screen and (orientation: landscape) {
	background-color: yellow;
	color: red;
}

@media screen and (orientation: portrait) {
	background-color: blue;
	color: green;
}
```

### 4. Not helped

I can’t find how I can get the expected behavior, use:

1. [**Built-in Bulma breakpoints**](https://bulma.io/documentation/start/responsiveness/#breakpoints)
1. [**PostCSS plugins**](https://github.com/postcss/postcss#plugins) and [**Stylelint plugins**](https://github.com/stylelint/awesome-stylelint#plugins).

If you decide to close this issue, please let me know how to resolve the problem.

Thanks.
